import = ["/home/rph/.config/alacritty/themes/gruvbox_material_medium_dark.toml"]

[font]
size = 9.0

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[shell]
args = ["--login"]
program = "/bin/fish"
